# Numpy Vs List

In [2]:
import numpy as np

In [3]:
X = np.array( [ 3, 4, 5, 7, 8, 8, 23, 35 ] )

In [4]:
X

array([ 3,  4,  5,  7,  8,  8, 23, 35])

In [5]:
X[0]

3

In [6]:
X[0:4]

array([3, 4, 5, 7])

In [7]:
X[-1]

35

In [8]:
data = [21, 45, 67, "hello", "hey"]
x1 = np.array(data)  # upcasting

In [9]:
x1

array(['21', '45', '67', 'hello', 'hey'], dtype='<U21')

In [10]:
import sys

In [11]:
list_1 = list(range(10))

In [15]:
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
sys.getsizeof(list_1)

208

In [13]:
arr_1 = np.array(list_1)

In [14]:
sys.getsizeof(arr_1)

176

In [16]:
sys.getsizeof(list())

72

In [17]:
sys.getsizeof(0)

24

In [18]:
sys.getsizeof(1)

28

In [19]:
list_1 = list(range(100000))

In [20]:
arr_1 = np.array(list_1)

In [22]:
sys.getsizeof(list_1)

900120

In [23]:
sys.getsizeof(arr_1)

800096

In [24]:
sys.getsizeof(np.array([]))

96

## Ways to create array in Numpy

In [25]:
x1 = np.array([2 ,4 , 7, 8, 43, 56, 78, 32, 67])

In [26]:
print(x1)

[ 2  4  7  8 43 56 78 32 67]


In [27]:
x2 = np.array( [ i for i in range(1,100001) if i % 2 == 0] )

In [28]:
len(x2)

50000

In [29]:
x2[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [30]:
x3 = np.arange(2,10001,2)

In [31]:
len(x3)

5000

In [32]:
x3[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [37]:
# will return array of 50 numbers starting from 1.0 to 10.0 (default)
# will return array of 20 numbers starting from 1.0 to 10.0
x4 = np.linspace(1,10, num=20, retstep=True)

In [38]:
x4

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [39]:
np.random.rand()

0.2827415502912186

In [40]:
np.random.rand(2)

array([0.79496222, 0.80003153])

In [41]:
np.random.rand(2,5)

array([[0.94877498, 0.38861311, 0.91119159, 0.69955595, 0.9543905 ],
       [0.07357738, 0.60233545, 0.19140364, 0.98438507, 0.82221879]])

In [42]:
# wil return 5 random numbers between 10 and 100
np.random.randint(10,100,5)

array([50, 47, 79, 33, 32])

In [43]:
np.random.seed(5)

In [44]:
np.random.randint(10,100,5)

array([88, 71, 26, 83, 18])

In [45]:
np.random.rand()

0.08982103773760686