# Numpy Vs List

In [1]:
import numpy as np

In [2]:
X = np.array( [ 3, 4, 5, 7, 8, 8, 23, 35 ] )

In [3]:
X

array([ 3,  4,  5,  7,  8,  8, 23, 35])

In [4]:
X[0]

3

In [5]:
X[0:4]

array([3, 4, 5, 7])

In [6]:
X[-1]

35

In [7]:
data = [21, 45, 67, "hello", "hey"]
x1 = np.array(data)  # upcasting

In [8]:
x1

array(['21', '45', '67', 'hello', 'hey'], dtype='<U21')

In [9]:
import sys

In [10]:
list_1 = list(range(10))

In [11]:
list_1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
sys.getsizeof(list_1)

208

In [13]:
arr_1 = np.array(list_1)

In [14]:
sys.getsizeof(arr_1)

176

In [15]:
sys.getsizeof(list())

72

In [16]:
sys.getsizeof(0)

24

In [17]:
sys.getsizeof(1)

28

In [18]:
list_1 = list(range(100000))

In [19]:
arr_1 = np.array(list_1)

In [20]:
sys.getsizeof(list_1)

900120

In [21]:
sys.getsizeof(arr_1)

800096

In [22]:
sys.getsizeof(np.array([]))

96

## Ways to create array in Numpy

In [23]:
x1 = np.array([2 ,4 , 7, 8, 43, 56, 78, 32, 67])

In [24]:
print(x1)

[ 2  4  7  8 43 56 78 32 67]


In [25]:
x2 = np.array( [ i for i in range(1,100001) if i % 2 == 0] )

In [26]:
len(x2)

50000

In [27]:
x2[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
x3 = np.arange(2,10001,2)

In [29]:
len(x3)

5000

In [30]:
x3[:10]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
# will return array of 50 numbers starting from 1.0 to 10.0 (default)
# will return array of 20 numbers starting from 1.0 to 10.0
x4 = np.linspace(1,10, num=20, retstep=True)

In [33]:
x4

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [34]:
np.random.rand()

0.23751764107600504

In [35]:
np.random.rand(2)

array([0.55167078, 0.25506633])

In [36]:
np.random.rand(2,5)

array([[0.72218551, 0.87327582, 0.33986832, 0.1960693 , 0.61960718],
       [0.48713272, 0.29948063, 0.78914686, 0.36120428, 0.46328417]])

In [37]:
# wil return 5 random numbers between 10 and 100
np.random.randint(10,100,5)

array([80, 51, 57, 24, 48])

In [38]:
np.random.seed(5)

In [39]:
np.random.randint(10,100,5)

array([88, 71, 26, 83, 18])

In [40]:
np.random.rand()

0.08982103773760686

In [42]:
np.random.random( [5,5] )

array([[0.39673661, 0.35413804, 0.486638  , 0.99082093, 0.80828168],
       [0.64945888, 0.81947279, 0.24254041, 0.76437261, 0.11090076],
       [0.20415475, 0.11909536, 0.87790307, 0.52367529, 0.492136  ],
       [0.7318711 , 0.01458075, 0.09336303, 0.82655425, 0.83349274],
       [0.89241102, 0.9580135 , 0.56133712, 0.0905487 , 0.99598891]])

In [44]:
np.random.rand(2,5,3)

array([[[0.34489264, 0.70854581, 0.67050971],
        [0.69335062, 0.13892684, 0.70068456],
        [0.4441239 , 0.57737515, 0.35492879],
        [0.58676919, 0.00331044, 0.06326857],
        [0.08154456, 0.50042232, 0.54838953]],

       [[0.69878002, 0.45500455, 0.5525777 ],
        [0.28472523, 0.94624035, 0.83593806],
        [0.39266062, 0.93333912, 0.00506349],
        [0.49245361, 0.37799671, 0.80064205],
        [0.40761409, 0.28897129, 0.93283075]]])

## Methods of Numpy

In [45]:
x = np.random.randint(10,1000,200)

In [46]:
x

array([278,  31, 967, 680, 929, 853, 281, 703, 913, 883, 813, 713, 391,
       818, 320, 301, 679, 641, 117, 575, 581, 369, 571, 953, 508,  85,
        27, 634, 808, 776, 286, 582,  47, 456, 529, 599, 528, 789, 399,
        89, 887, 587, 337, 137, 687, 995, 933, 982, 425,  42, 398, 322,
        37, 104, 375, 853, 742, 756, 139, 449, 821, 126, 813, 712, 875,
       580, 144,  84, 512, 657, 209, 654, 673, 248, 692, 595, 799, 870,
        87, 160, 198, 909, 997, 987, 752, 832, 898, 354, 412, 350, 899,
        65, 929, 751, 960, 683,  12, 546, 284, 253, 776, 179, 889, 217,
        33, 157, 538, 213, 466, 799, 339, 270, 874, 917, 208, 676, 912,
       383, 155, 210, 902, 436, 197, 231,  67, 715, 499, 933, 321, 277,
       183, 920, 173, 333, 382, 742, 685, 653, 467,  47, 545, 746, 725,
       753, 745, 489, 605, 396, 178, 396, 184, 291,  76,  94, 393, 724,
        24, 940,  44, 812, 972, 738, 152, 974, 769, 347, 289, 696, 459,
       682, 370,  34,  33, 415, 439,  69, 668, 871, 715, 911, 98

In [47]:
x.max()

997

In [48]:
x.min()

12

In [49]:
x.mean()

511.11

In [50]:
x.shape

(200,)

In [51]:
x.ndim

1

In [52]:
x.argmax()

82

In [53]:
x[82]

997

In [54]:
x.argmin()

96

In [55]:
x[96]

12

In [57]:
x.argsort()[:10]

array([ 96, 156,  26, 189,   1, 104, 172, 171,  52,  49])

In [67]:
x[49]

42

## Slicing Numpy Array

In [68]:
x = np.array([ [ 4,5,3,2 ], [ 6,8,3,6 ], [ 8,8,4,7 ] ])

In [69]:
x

array([[4, 5, 3, 2],
       [6, 8, 3, 6],
       [8, 8, 4, 7]])

In [70]:
x.ndim

2

In [71]:
x.shape

(3, 4)

In [72]:
#In 2D array, by default, slicing will be row wise
x[0:2]

array([[4, 5, 3, 2],
       [6, 8, 3, 6]])

In [73]:
x[0:2,0:2]

array([[4, 5],
       [6, 8]])

In [74]:
x[:,0:2]

array([[4, 5],
       [6, 8],
       [8, 8]])